// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4q6RE3EAebku4_UUf58hIsN6SOKj3Cpk',
    appId: '1:421928915129:web:664100a58807dc29348b68',
    messagingSenderId: '421928915129',
    projectId: 'demofb-f9710',
    authDomain: 'demofb-f9710.firebaseapp.com',
    storageBucket: 'demofb-f9710.appspot.com',
    measurementId: 'G-R90ZT4QVZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnPRVJjYql5N-2Mrtq_p2yZzhCNtWFpAI',
    appId: '1:421928915129:android:a15ea1697ca65dc6348b68',
    messagingSenderId: '421928915129',
    projectId: 'demofb-f9710',
    storageBucket: 'demofb-f9710.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQX3gakgUDX63-CfIyq5v-GUylzRBhtTs',
    appId: '1:421928915129:ios:dc625c53b048ed29348b68',
    messagingSenderId: '421928915129',
    projectId: 'demofb-f9710',
    storageBucket: 'demofb-f9710.appspot.com',
    iosBundleId: 'com.example.demofb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQX3gakgUDX63-CfIyq5v-GUylzRBhtTs',
    appId: '1:421928915129:ios:9bd0115c7f5b85d6348b68',
    messagingSenderId: '421928915129',
    projectId: 'demofb-f9710',
    storageBucket: 'demofb-f9710.appspot.com',
    iosBundleId: 'com.example.demofb.RunnerTests',
  );
}
